version: "3.8"

services:
  movies-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
