name: Deploy Movies App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install and build
        run: |
          cd frontend
          npm install
          npm run build
        env:
          VITE_API_URL: https://atomic-fs-test.onrender.com/api/movies

      - name: Deploy
        run: |
          cd frontend
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp -r dist/* ../
          cd ..
          git add index.html assets/
          git commit -m "Deploy frontend" || exit 0
          git push origin main
